apiMap:
  team:
    api: mlbapi
    format: json
    team: team_id
    sleep: 0
  roster_40:
    api: mlbapi
    format: json
    team: team_id
    sleep: 0
  roster_past:
    api: mlbapi
    format: json
    team: team_id
    sleep: 0
  transaction:
    api: mlbapi
    format: json
    team: team_id
    sleep: 0
    dates:
      params: ['start_date','end_date']
      format: interval
      delim: ''
  player:
    api: mlbapi
    format: json
    team: team_id
    sleep: 0
  atbat:
    api: savant
    format: csv
    team: abbr
    sleep: 30
    dates:
      params: ['game_date_lt','game_date_gt']
      format: interval
      delim: ''
  playbyplay:
    api: mlbstats
    format: json
    sleep: 0
  schedule:
    api: mlbstats
    format: json
    sleep: 0
    dates:
      params: ['startDate','endDate']
      format: interval
      delim: '-'
    data: ['dates','games']
mlbapi:
  base: http://lookup-service-prod.mlb.com/json/named.
  endpoints:
    team:
      template: team_all_season.bam?all_star_sw='N'&sort_order=name_asc
      params:
    roster_40:
      template: roster_40.bam?
      params:
        - team_id
    roster_past:
      template: roster_team_alltime.bam?'
      params:
        - team_id
        - start_season
        - end_season
    transaction:
      template: transaction_all.bam?sport_code='mlb'
      params:
        - start_date
        - end_date
    player:
      template: player_info.bam?sport_code='mlb'
      params:
        - player_id
savant:
  base: https://baseballsavant.mlb.com/
  endpoints:
    atbat:
      template: statcast_search/csv?all=true&hfGT=R%7C&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0&type=details
      params:
        - hfSea
        - team
mlbstats:
  base: http://statsapi.mlb.com/api/v1/
  endpoints:
    playbyplay:
      template: game/{game_pk}/playByPlay
      pathParams:
        - game_pk
    schedule:
      template: schedule/games/?sportId=1
      params:
       - season
       - startDate
       - endDate


