##Run using seed_dd.py script
extract:
  sources:
    player:
      params:
        player_id: ['ALL']
    ##Which seasons and teams to get at bat data for
    ##Can specify date ranges to narrow further
    playbyplay:
      pathParams:
        game_pk: ['All']
  ##Where to store csv and json data from API calls.
  output:
    dir: temp_data/
    locations:
      player: player/
      playbyplay: playbyplay
transform:
  types:
    - player
    - plays
load:
  player: 'upsert'
  plays: 'upsert'
sql_statements:
  dir: 'sql/create_tables'
  scripts:
    - game_events.sql