urls:
  team: http://lookup-service-prod.mlb.com/json/named.team_all_season.bam?all_star_sw='N'&sort_order=name_asc
  roster_40: http://lookup-service-prod.mlb.com/json/named.roster_40.bam?
  roster_past: http://lookup-service-prod.mlb.com/json/named.roster_team_alltime.bam?'
  transaction: http://lookup-service-prod.mlb.com/json/named.transaction_all.bam?sport_code='mlb'
  player: http://lookup-service-prod.mlb.com/json/named.player_info.bam?sport_code='mlb'
  atbat: https://baseballsavant.mlb.com/statcast_search/csv?all=true&
format:
  team: json
  roster_40: json
  roster_past: json
  transaction: json
  player: json
  atbat: csv
tables:
  team:
    schema: league
    table: teams
  roster_40:
    schema: rosters
    table: roster_40
  roster_past:
    schema: rosters
    table: historical_rosters
  transaction:
    schema: rosters
    table: transactions
  player:
    schema: rosters
    table: players
  play_by_play:
    schema: league
    table: play_by_play






