CREATE TABLE league.play_by_play
(
    pitch_type text COLLATE pg_catalog."default",
    game_date date,
    release_speed numeric(4,1),
    release_pos_x numeric(7,4),
    release_pos_z numeric(6,4),
    player_name text COLLATE pg_catalog."default",
    batter integer,
    pitcher integer,
    events text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    spin_dir text COLLATE pg_catalog."default",
    spin_rate_deprecated numeric(7,4),
    break_angle_deprecated numeric(7,4),
    break_length_deprecated numeric(7,4),
    zone numeric(3,0),
    des text COLLATE pg_catalog."default",
    game_type text COLLATE pg_catalog."default",
    stand text COLLATE pg_catalog."default",
    p_throws text COLLATE pg_catalog."default",
    home_team text COLLATE pg_catalog."default",
    away_team text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    hit_location numeric(7,4),
    bb_type text COLLATE pg_catalog."default",
    balls integer,
    strikes integer,
    game_year text COLLATE pg_catalog."default",
    pfx_x numeric(7,4),
    pfx_z numeric(6,4),
    plate_x numeric(6,4),
    plate_z numeric(6,4),
    on_3b numeric(8,0),
    on_2b numeric(8,0),
    on_1b numeric(8,0),
    outs_when_up integer,
    inning integer,
    inning_topbot text COLLATE pg_catalog."default",
    hc_x numeric(6,2),
    hc_y numeric(5,2),
    tfs_deprecated text COLLATE pg_catalog."default",
    tfs_zulu_deprecated text COLLATE pg_catalog."default",
    fielder_2 numeric(8,0),
    umpire text COLLATE pg_catalog."default",
    sv_id text COLLATE pg_catalog."default",
    vx0 numeric(6,4),
    vy0 numeric(9,4),
    vz0 numeric(7,4),
    ax numeric(8,4),
    ay numeric(7,4),
    az numeric(8,4),
    sz_top numeric(6,4),
    sz_bot numeric(6,4),
    hit_distance_sc numeric(7,4),
    launch_speed numeric(5,1),
    launch_angle numeric(4,1),
    effective_speed numeric(7,4),
    release_spin_rate numeric(6,2),
    release_extension numeric(6,4),
    game_pk integer,
    fielder_3 numeric(8,0),
    fielder_4 numeric(8,0),
    fielder_5 numeric(8,0),
    fielder_6 numeric(8,0),
    fielder_7 numeric(8,0),
    fielder_8 numeric(8,0),
    fielder_9 numeric(8,0),
    release_pos_y numeric(7,4),
    estimated_ba_using_speedangle numeric(5,3),
    estimated_woba_using_speedangle numeric(5,3),
    woba_value numeric(4,2),
    woba_denom numeric(5,3),
    babip_value numeric(5,3),
    iso_value numeric(5,3),
    launch_speed_angle numeric(7,4),
    at_bat_number integer,
    pitch_number integer,
    pitch_name text COLLATE pg_catalog."default",
    home_score integer,
    away_score integer,
    bat_score integer,
    fld_score integer,
    post_away_score integer,
    post_home_score integer,
    post_bat_score integer,
    post_fld_score integer,
    if_fielding_alignment text COLLATE pg_catalog."default",
    of_fielding_alignment text COLLATE pg_catalog."default"
)