DROP TABLE IF EXISTS rosters.players;

CREATE TABLE rosters.players (
	birth_country text NULL,
	name_prefix text NULL,
	name_display_first_last text NULL,
	college text NULL,
	height_inches int4 NULL,
	death_country text NULL,
	age int4 NULL,
	name_display_first_last_html text NULL,
	gender text NULL,
	height_feet int4 NULL,
	pro_debut_date text NULL,
	death_date text NULL,
	primary_position text NULL,
	birth_date text NULL,
	team_abbrev text NULL,
	status text NULL,
	name_display_last_first_html text NULL,
	throws text NULL,
	death_city text NULL,
	primary_position_txt text NULL,
	high_school text NULL,
	name_display_roster_html text NULL,
	name_use text NULL,
	player_id int4 NOT NULL,
	status_date text NULL,
	primary_stat_type text NULL,
	team_id int4 NULL,
	active_sw text NULL,
	primary_sport_code text NULL,
	birth_state text NULL,
	weight int4 NULL,
	name_middle text NULL,
	name_display_roster text NULL,
	end_date text NULL,
	jersey_number float8 NULL,
	death_state text NULL,
	name_first text NULL,
	bats text NULL,
	team_code text NULL,
	birth_city text NULL,
	name_nick text NULL,
	status_code text NULL,
	name_matrilineal text NULL,
	team_name text NULL,
	name_display_last_first text NULL,
	twitter_id text NULL,
	name_title text NULL,
	file_code text NULL,
	name_last text NULL,
	start_date text NULL,
	name_full text NULL,
	CONSTRAINT players_pkey PRIMARY KEY (player_id)
);

