DROP TABLE IF EXISTS rosters.roster_40;

CREATE TABLE rosters.roster_40 (
	position_txt text NULL,
	weight int4 NULL,
	name_display_first_last text NULL,
	college text NULL,
	height_inches int4 NULL,
	starter_sw text NULL,
	jersey_number int4 NULL,
	end_date date NULL,
	name_first text NULL,
	bats text NULL,
	team_code text NULL,
	height_feet int4 NULL,
	pro_debut_date date NULL,
	status_code text NULL,
	primary_position text NULL,
	birth_date date NULL,
	team_abbrev text NULL,
	throws text NULL,
	team_name text NULL,
	name_display_last_first text NULL,
	name_use text NULL,
	player_id int4 NULL,
	name_last text NULL,
	team_id int4 NULL,
	start_date text NULL,
	name_full text NULL,
	added_timestamp timestamp NOT NULL default NOW()
);
