CREATE TABLE IF NOT EXISTS league.teams(
   phone_number         VARCHAR(30)
  ,venue_name           VARCHAR(30)
  ,franchise_code       VARCHAR(30)
  ,all_star_sw          VARCHAR(30)
  ,sport_code           VARCHAR(30)
  ,address_city         VARCHAR(30)
  ,city                 VARCHAR(30)
  ,name_display_full    VARCHAR(30)
  ,spring_league_abbrev VARCHAR(30)
  ,time_zone_alt        VARCHAR(30)
  ,sport_id             INTEGER
  ,venue_id             INTEGER
  ,mlb_org_id           INTEGER
  ,time_zone_generic    VARCHAR(30)
  ,mlb_org              VARCHAR(30)
  ,last_year_of_play    INTEGER
  ,league_full          VARCHAR(30)
  ,home_opener_time     VARCHAR(30)
  ,address_province     VARCHAR(30)
  ,league_id            INTEGER
  ,name_abbrev          VARCHAR(30)
  ,bis_team_code        VARCHAR(30)
  ,league               VARCHAR(30)
  ,spring_league        VARCHAR(30)
  ,base_url             VARCHAR(30)
  ,address_zip          VARCHAR(30)
  ,sport_code_display   VARCHAR(30)
  ,mlb_org_short        VARCHAR(30)
  ,time_zone            VARCHAR(30)
  ,address_line1        VARCHAR(30)
  ,mlb_org_brief        VARCHAR(30)
  ,address_line2        VARCHAR(30)
  ,season               INTEGER
  ,address_line3        VARCHAR(30)
  ,division_abbrev      VARCHAR(30)
  ,name_display_short   VARCHAR(30)
  ,team_id              INTEGER PRIMARY KEY
  ,active_sw            VARCHAR(30)
  ,address_intl         VARCHAR(30)
  ,state                VARCHAR(30)
  ,address_country      VARCHAR(30)
  ,mlb_org_abbrev       VARCHAR(30)
  ,division             VARCHAR(30)
  ,team_code            VARCHAR(30)
  ,name                 VARCHAR(30)
  ,website_url          VARCHAR(30)
  ,sport_code_name      VARCHAR(30)
  ,first_year_of_play   INTEGER
  ,league_abbrev        VARCHAR(30)
  ,name_display_long    VARCHAR(30)
  ,store_url            VARCHAR(30)
  ,time_zone_text       VARCHAR(30)
  ,name_short           VARCHAR(30)
  ,home_opener          VARCHAR(30)
  ,address_state        VARCHAR(30)
  ,division_full        VARCHAR(30)
  ,time_zone_num        INTEGER
  ,spring_league_full   VARCHAR(30)
  ,address              VARCHAR(30)
  ,name_display_brief   VARCHAR(30)
  ,file_code            VARCHAR(30)
  ,division_id          INTEGER
  ,spring_league_id     INTEGER
  ,venue_short          VARCHAR(30)
);