CREATE TABLE league.events (
    "starttime" timestamp NULL,
    "endtime" timestamp NULL,
    "ispitch" boolean NULL,
    "type" varchar(50),
    "details_description" text NULL,
    "details_event" text NULL,
    "details_eventtype" varchar(500) NULL,
    "details_awayscore" int4 NULL ,
    "details_homescore" int4 NULL,
    "details_isscoringplay" boolean NULL,
    "details_hasreview" boolean NULL,
    "count_balls" int4 NULL,
    "count_strikes" int4 NULL,
    "count_outs" int4 NULL,
    "player_id" int4 NULL,
    "player_link" varchar(500) NULL,
    "pfxid" int NULL,
    "playid" int NULL,
    "pitchnumber" int4 NULL,
    "details_call_code" varchar(10) NULL,
    "details_call_description" varchar(100) NULL,
    "details_code" varchar(100) NULL,
    "details_ballcolor" varchar(500) NULL,
    "details_trailcolor" varchar(500) NULL,
    "details_isinplay" boolean NULL,
    "details_isstrike" boolean NULL,
    "details_isball" boolean NULL,
    "details_type_code" varchar(10) NULL,
    "details_type_description" text NULL,
    "pitchdata_startspeed" float NULL,
    "pitchdata_endspeed" float NULL,
    "pitchdata_strikezonetop" float NULL,
    "pitchdata_strikezonebottom" float NULL,
    "pitchdata_coordinates_ay" float NULL,
    "pitchdata_coordinates_az" float NULL,
    "pitchdata_coordinates_pfxx" float NULL,
    "pitchdata_coordinates_pfxz" float NULL,
    "pitchdata_coordinates_px" float NULL,
    "pitchdata_coordinates_pz" float NULL,
    "pitchdata_coordinates_vx0" float NULL,
    "pitchdata_coordinates_vy0" float NULL,
    "pitchdata_coordinates_vz0" float NULL,
    "pitchdata_coordinates_x" float NULL,
    "pitchdata_coordinates_y" float NULL,
    "pitchdata_coordinates_x0" float NULL,
    "pitchdata_coordinates_y0" float NULL,
    "pitchdata_coordinates_z0" float NULL,
    "pitchdata_coordinates_ax" float NULL,
    "pitchdata_breaks_breakangle" float NULL,
    "pitchdata_breaks_breaklength" float NULL,
    "pitchdata_breaks_breaky" float NULL,
    "pitchdata_breaks_spinrate" float NULL,
    "pitchdata_breaks_spindirection" float NULL,
    "pitchdata_zone" float NULL,
    "pitchdata_typeconfidence" float NULL,
    "pitchdata_platetime" float NULL,
    "pitchdata_extension" float NULL,
    "hitdata_launchspeed" float NULL,
    "hitdata_launchangle" float NULL,
    "hitdata_totaldistance" float NULL,
    "hitdata_trajectory" varchar(200) NULL,
    "hitdata_hardness" varchar(10) NULL,
    "hitdata_location" int NULL,
    "hitdata_coordinates_coordx" float NULL,
    "hitdata_coordinates_coordy" float NULL,
    "details_fromcatcher" boolean NULL,
    "position_code" int NULL,
    "position_name" varchar(100) NULL,
    "position_type" varchar(100) NULL,
    "position_abbreviation" varchar(100) NULL,
    "battingorder" int NULL,
    "details_runnergoing" boolean NULL,
    "result_event" text,
    "actionplayid" varchar(500) NULL,
    "base" int NULL,
    "injurytype" varchar(200)NULL,
    "umpire_id" int NULL,
    "umpire_link" varchar(500) NULL,
    "reviewdetails_isoverturned" boolean NULL ,
    "reviewdetails_reviewtype" varchar(10) NULL,
    "reviewdetails_challengeteamid" int,
    "game_pk" int
);