CREATE TABLE league.schedule(
  gamePk int,
  link varchar(120),
  gameType varchar(8),
  season int,
  gameDate timestamp,
  officialDate date,
  isTie boolean,
  gameNumber int,
  publicFacing boolean ,
  doubleHeader varchar(8),
  gamedayType varchar(8),
  tiebreaker varchar(8),
  calendarEventID varchar(120),
  seasonDisplay int,
  dayNight varchar(8),
  scheduledInnings int,
  inningBreakLength int ,
  gamesInSeries int,
  seriesGameNumber int,
  seriesDescription varchar(200),
  recordSource varchar(10),
  ifNecessary varchar(8) ,
  ifNecessaryDescription varchar(200),
  status.abstractGameState, varchar(120),
  status.codedGameState varchar(12),
  status.detailedState varchar(120) ,
  status.statusCode varchar(12),
  status.abstractGameCode varchar(12),
  teams.away.leagueRecord.wins int,
  teams.away.leagueRecord.losses int,
  teams.away.leagueRecord.pct float,
  teams.away.score int,
  teams.away.team.id int,
  teams.away.team.name varchar(200),
  teams.away.team.link varchar(120),
  teams.away.isWinner boolean,
  teams.away.splitSquad boolean,
  teams.away.seriesNumber int,
  teams.home.leagueRecord.wins int,
  teams.home.leagueRecord.losses int,
  teams.home.leagueRecord.pct float,
  teams.home.score int,
  teams.home.team.id int,
  teams.home.team.name varchar(200),
  teams.home.team.link varcahr(120),
  teams.home.isWinner boolean,
  teams.home.splitSquad boolean,
  teams.home.seriesNumber int,
  venue.id int,
  venue.name varchar(400),
  venue.link varchar(120),
  content.link varchar(250),
  status.reason varchar(120),
  description varchar(1000),
  rescheduleDate timestamp,
  rescheduledFrom timestamp,
  status.startTimeTBD boolean,
  resumeDate timestamp,
  resumedFrom timestamp
)